---
name: Build and test
on:
  pull_request:
    paths:
      - .github/workflows/build-and-test.yml
      - '**/*.rs'
      - Cargo.toml
      - Cargo.lock
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: --deny warnings

jobs:
  build-and-test:
    strategy:
      matrix:
        rust: [stable, beta, nightly, 1.56.0]
    runs-on: ubuntu-latest
    steps:
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libnftnl-dev libmnl-dev

      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af #v1.0.7
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          default: true

      - name: Build
        run: cargo build --all-targets --locked

      - name: Test
        run: cargo test

  # Make sure the library builds with all dependencies downgraded to their
  # oldest versions allowed by the semver spec. This ensures we have not
  # under-specified any dependency
  minimal-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libnftnl-dev libmnl-dev

      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af #v1.0.7
        with:
          toolchain: nightly
          profile: minimal
          default: true

      - name: Downgrade dependencies to minimal versions
        run: cargo +nightly update -Z minimal-versions

      - name: Compile with minimal versions
        run: cargo build --all-targets
